# Generated by Django 3.1.7 on 2021-04-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20210331_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
