# Generated by Django 3.1.7 on 2021-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.CharField(choices=[('UG', 'UG'), ('PG', 'PG')], max_length=100),
        ),
    ]
