# Generated by Django 3.1.7 on 2021-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_audit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('attendance', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='absent', max_length=150)),
            ],
        ),
    ]
