# Generated by Django 3.1.7 on 2021-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
