# Generated by Django 3.1.7 on 2021-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
