# Generated by Django 3.1.7 on 2021-04-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20210402_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
